# Generated by Django 5.2.14 on 2026-05-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Extra markup the agent added', max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='middleware_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Supplier price + platform commission (before agent markup)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='booking',
            name='agent_price',
            field=models.DecimalField(decimal_places=2, help_text='Final price charged to the agent (middleware + additional)', max_digits=12),
        ),
    ]
