# Generated by Django 5.2.14 on 2026-05-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking_agent_markup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='additional_commission',
        ),
        migrations.AddField(
            model_name='booking',
            name='agent_commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Extra commission the agent added', max_digits=12),
        ),
        migrations.AlterField(
            model_name='booking',
            name='agent_price',
            field=models.DecimalField(decimal_places=2, help_text='Final price charged to the agent (middleware + agent commission)', max_digits=12),
        ),
    ]
