# Generated by Django 5.2.14 on 2026-05-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_agent_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='prebook_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
