# Generated by Django 5.2.14 on 2026-05-18 00:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier', models.CharField(choices=[('nuitee', 'nuitee'), ('sideminder', 'sideminder'), ('expedia', 'expedia')], max_length=32)),
                ('external_booking_id', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('prebooked', 'prebooked'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled')], max_length=32)),
                ('hotel_id', models.CharField(max_length=64)),
                ('guest_name', models.CharField(max_length=256)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='SupplierModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('nuitee', 'nuitee'), ('sideminder', 'sideminder'), ('expedia', 'expedia')], max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
    ]
